AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'vendor/bundle'
    - 'db/schema.rb'
    - vendor/**/*.rb
    - vendor/bundle/**/*
Style/Documentation:
        Enabled: false
Style/MixinUsage:
        Enabled: false
